openapi: 3.0.3
info:
  title: Donation app REST API
  description: Donation app REST API
  version: 1.0.0
servers:
  - url: 'https://donationapp.dev.com/'
paths:
  /charities:
    get:
      summary: list all charities of the app
      responses:
        '200':
          description: list of charities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                    description:
                      type: string
                    category:
                      type: string



